mongo:
#  image: terbooter/mongo
  build: .
  ports:
    - "27017:27017"
  volumes:
    - ./data/db:/data/db
  restart: "always"
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "100"
  env_file: .env